org: 12jikan
service: nat20

provider:
    name: aws
    runtime: nodejs20.x
    region: us-east-1
    memorySize: 1024
    timeout: 30
    apiGateway:
        # restApi: 'asdasd'
        description: 'My User Authentication Service'

package:
    individually: false
    exclude:
        - '**/**' # Excludes everything by default
        - '!src/**' # Then include only what you need
    include:
        - .env

functions:
    create_user:
        description: 'Create a new user'
        handler: src/auth_handlers/auth.create_account
        events:
            - http:
                  cors:
                      origin: '*'
                      maxAge: 86400
                  path: users
                  method: post

    confirm_user:
        description: 'Confirm a new user'
        handler: src/auth_handlers/auth.confirm_user
        events:
            - cognitoUserPool:
                  pool: nat20-users
                  trigger: PreSignUp

    signin_user:
        description: 'Sign in a user'
        handler: src/auth_handlers/auth.signin_user
        events:
            - http:
                  cors:
                      origin: '*'
                      maxAge: 86400
                  path: login
                  method: post
                  #   timeout: 1800
