org: 12jikan
service: nat20

provider:
    name: aws
    runtime: nodejs20.x
    region: us-east-1
    memorySize: 128
    timeout: 30
    apiGateway:
        restApi:
        description: 'My User Authentication Service'

package:
    individually: false
    exclude:
        - '**/**' # Excludes everything by default
        - '!src/**' # Then include only what you need

functions:
    create_user:
        description: 'Create a new user'
        handler: src/auth_handlers/auth.create_account
        events:
            - http:
                  cors: true
                  path: users
                  method: post
